# URL for your bucket page, with a trailing slash
base_url = "https://www.example.changeme/"

# The title of the page.
title = "Studio Name"

# This is text that goes above the games, in Markdown format (HTML can also be used).
description = """
# Studio Name

We make games and then we put them in a bucket.
"""

# Whether to enable your RSS feed
enable_rss = false

# Language for your site (currently only used for RSS)
lang_code = "en"

# Custom CSS for the page.
css = """
/* CSS goes here. */
"""

# Custom JavaScript for the page.
js = """
// JavaScript goes here.
"""
