# The title of the page.
title = "Game Name"

# A short blurb about the game, used in the bucket page, in Markdown format.
short = "A new game."

# This is text that goes above the games, in Markdown format (HTML can also be used!).
description = """
A new game - but far from the last one.
"""

# Optional author information
#author="Cool Author"
#author_link="https://mycoolwebsite.example.com" # use "" to disable, defaults to a generated author page
#author_blurb="""Some Markdown text about the author"""

#author_file="coolauthor.toml" # Contains reusable author info. Will look for pybucketgames/authors/[author_name_with_underscores].toml . Deprecated. 
#author_pic="coolauthor.png" # will look for an "author" img by default, but this can be added to the author_file and reused. Relative to the toml file it's set in

#platforms = "PC, Mac, and Linux"

#made_with = ""


# The license for the game, in markdown format.
# license = """
# License text goes here.
# """

# Custom CSS for the page.
css = """
/* CSS goes here. */
"""

# Custom JavaScript for the page.
js = """
// JavaScript goes here.
"""

# Defaults to the date of the last modified file
#date = "1-1-2025"
